# Agent Memory Context Graph Application
# Generated by create-context-graph

-include .env
export

.PHONY: start dev dev-backend dev-frontend install schema seed reset test-connection triage-check triage-enrich-full triage-load triage-load-decision triage-similarity clean test test-e2e lint docker-build docker-prod-up docker-prod-down

# Start both backend and frontend
start:
	@echo "Starting Agent Memory Context Graph..."
	@trap 'kill 0' EXIT; \
		$(MAKE) dev-backend & \
		$(MAKE) dev-frontend & \
		wait

dev: start

# Backend
dev-backend:
	cd backend && uv run uvicorn app.main:app --reload --port $${BACKEND_PORT:-8000}

install-backend:
	cd backend && uv sync
	cd backend && uv run python -m spacy download en_core_web_sm

# Frontend
dev-frontend:
	cd frontend && NEXT_PUBLIC_API_URL=http://localhost:$${BACKEND_PORT:-8000}/api npm run dev -- --port $${FRONTEND_PORT:-3000}

install-frontend:
	cd frontend && npm install

# Install everything
install: install-backend install-frontend

# Legacy scaffold command: applies Agent Memory scaffold schema (cypher/schema.cypher).
# Do not use for the active TriageFix demo workflow.
schema:
	@echo "WARNING: 'make schema' is a legacy Agent Memory scaffold command."
	@echo "WARNING: For TriageFix demo, use 'make triage-load' and 'make triage-similarity' instead."
	cd backend && uv run python -c "import asyncio; from scripts.generate_data import apply_schema; asyncio.run(apply_schema())"

# Legacy scaffold command: applies Agent Memory fixtures from data/fixtures.json.
# Do not use for the active TriageFix demo workflow.
seed:
	@echo "WARNING: 'make seed' is a legacy Agent Memory fixture command."
	@echo "WARNING: For TriageFix demo, use 'make triage-load' and 'make triage-similarity' instead."
	cd backend && uv run python scripts/generate_data.py

# Destructive command: resets Neo4j data (drop and recreate).
# Do not run unless you explicitly intend to destroy and recreate graph data.
reset:
	@echo "DANGER: 'make reset' is destructive and will drop/recreate Neo4j data."
	cd backend && uv run python -c "from app.context_graph_client import reset_database; import asyncio; asyncio.run(reset_database())"

# Test Neo4j connection
test-connection:
	@cd backend && uv run python -c "import asyncio; from app.context_graph_client import connect_neo4j; asyncio.run(connect_neo4j()); print('Neo4j connection successful')" \
		|| echo "Connection failed. Check NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD in .env"

# TriageFix read-only check (no data mutation)
triage-check:
	@echo "TriageFix graph source: $${TRIAGEFIX_GRAPH_SOURCE:-airtable_enriched_full}"
	@echo "TriageFix input CSV: $${TRIAGEFIX_GRAPH_INPUT_CSV:-data/processed/enriched_incidents_full.csv}"
	@$(MAKE) test-connection

# TriageFix full-data enrichment (regenerates enriched_incidents_full.*)
triage-enrich-full:
	cd backend && uv run python scripts/03_enrich_all_incidences_for_graph.py

# TriageFix active loader (replaces prior managed nodes for current source)
triage-load:
	@echo "Using TRIAGEFIX_GRAPH_INPUT_CSV=$${TRIAGEFIX_GRAPH_INPUT_CSV:-data/processed/enriched_incidents_full.csv}"
	@export TRIAGEFIX_GRAPH_INPUT_CSV="$${TRIAGEFIX_GRAPH_INPUT_CSV:-$$(pwd)/data/processed/enriched_incidents_full.csv}"; \
		cd backend && uv run python scripts/04_load_triagefix_graph.py

# TriageFix decision graph loader (same dataset/source, decision-specific nodes/edges)
triage-load-decision:
	@echo "Using TRIAGEFIX_GRAPH_INPUT_CSV=$${TRIAGEFIX_GRAPH_INPUT_CSV:-data/processed/enriched_incidents_full.csv}"
	@export TRIAGEFIX_GRAPH_INPUT_CSV="$${TRIAGEFIX_GRAPH_INPUT_CSV:-$$(pwd)/data/processed/enriched_incidents_full.csv}"; \
		cd backend && uv run python scripts/load_treafefix_decision.py

# TriageFix semantic similarity edge builder (SIMILAR_TO)
triage-similarity:
	cd backend && uv run python scripts/05_create_semantic_similarity_edges.py

# Docker Neo4j
docker-up:
	docker compose up -d

docker-down:
	docker compose down




# Test
test:
	cd backend && uv run python -m pytest tests/ -v 2>/dev/null || echo "No backend tests found"
	cd frontend && npm test 2>/dev/null || echo "No frontend tests found"

# End-to-end tests (requires backend + frontend running, and Playwright installed)
test-e2e:
	cd frontend && npx playwright install --with-deps chromium 2>/dev/null; npm run test:e2e

# Lint
lint:
	cd backend && uv run ruff check app/ 2>/dev/null || echo "Install ruff for linting: uv pip install ruff"
	cd frontend && npm run lint 2>/dev/null || echo "No frontend lint configured"

# Docker production deployment
docker-build:
	docker compose -f docker-compose.prod.yml build

docker-prod-up:
	docker compose -f docker-compose.prod.yml up -d

docker-prod-down:
	docker compose -f docker-compose.prod.yml down

# Clean build artifacts
clean:
	rm -rf backend/__pycache__ backend/.venv
	rm -rf frontend/.next frontend/node_modules
