/**
 * Domain configuration for Agent Memory
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "agent-memory",
  name: "Agent Memory",
  description: "AI agent conversation tracking, entity extraction, memory management, and tool usage analysis",
  tagline: "AI-powered Agent Intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export const NODE_COLORS: Record<string, string> = {"Agent": "#8b5cf6", "Conversation": "#0ea5e9", "Entity": "#f59e0b", "Event": "#f97316", "Location": "#a855f7", "Memory": "#10b981", "Object": "#eab308", "Organization": "#64748b", "Person": "#22c55e", "Session": "#6366f1", "ToolCall": "#ef4444"};

export const NODE_SIZES: Record<string, number> = {"Agent": 30, "Conversation": 25, "Entity": 20, "Event": 20, "Location": 20, "Memory": 20, "Object": 20, "Organization": 20, "Person": 20, "Session": 25, "ToolCall": 15};

export const DEFAULT_CYPHER = `MATCH (a:Agent)-[r]-(n) RETURN a, r, n LIMIT 100`;

export const SCHEMA_NODE_SIZE = 30;
export const SCHEMA_REL_COLOR = "#94a3b8";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [{"name": "Agent Introspection", "prompts": ["What does agent Alpha remember about the user\u0027s project preferences?", "Show me all entities that agent Alpha has extracted this week", "Which tools does agent Alpha use most frequently?"]}, {"name": "Conversation Analysis", "prompts": ["Summarize the key topics discussed across all conversations today", "Which conversations were escalated and why?", "Find conversations where the agent failed to resolve the user\u0027s request"]}, {"name": "Memory Management", "prompts": ["What are the most important memories stored by agent Alpha?", "Show me the entity graph extracted from recent conversations", "Which memories haven\u0027t been accessed in over 30 days?"]}];
